### ISSUE TITLE
create new variable from 2 other variables (e.g. difference of 2 variables)

### ISSUE THREAD

**Issue by annecori** [Hackout3/cleanr#2]
Hey again, 
would it be possible to implement an easy way to create a variable from several other variables, e.g. A = B - C ?
thanks
Anne

**Comment by richfitz** [comment]
OK, I think I can imagine how to do this now.

Currently we have:

``` yaml
<newcolumn>:
  - <from>: <oldcolumn>
  - <function>
```

and the function takes as the first argument the column given.  So we can extend this to write:

``` yaml
<newcolumn>:
  - <from>: [<oldcolumn1>, <oldcolumn2>]
  - <function>
```

which would pass both columns, as two arguments, to the function.  Should be easy enough and consistent with the single column interface.

Then for the case that you have you can just provide a function that deals with that special case as it's unlikely to be totally general.

At the same time I'll see if the anonymous function approach works so that we can provide something like:

``` yaml
<newcolumn>:
  - <from>: [<oldcolumn1>, <oldcolumn2>]
  - function(x, y) x + y
```

**Comment by annecori** [comment]
yes all works well as far as I can tell now - both the old functionalities and the new stuff as well!
